
set mach_avail_time {K_mach_RESOURCES};
set earliest_ready_machines;
param earliest_ready_mach;
set temp_mach_avail_time {K_mach_RESOURCES};
param x_heur {JOBS, K_mach_RESOURCES};

for {k in K_mach_RESOURCES} let mach_avail_time := a_disc[k];

for {j in JOBS} {
let earliest_ready_machines := {k in K_mach_RESOURCES: mach_avail_time[k] == min{i in K_mach_RESOURCES} mach_avail_time[i]};
let earliest_ready_mach := first(earliest_ready_machines);

repeat while lambda_mach[j,earliest_ready_mach] == 0 {
       let temp_mach_avail_time := mach_avail_time;
       let temp_mach_avail_time[earliest_ready_mach] := Infinity;
       let earliest_mach_avail_time := {k in K_mach_RESOURCES: temp_mach_avail_time[k] == min{i in K_mach_RESOURCES} temp_mach_avail_time[i]};
       let earliest_ready_mach := first(earliest_ready_machines);
}

let x[j,earliest_ready_machine] := 1;
let mach_avail_time[earliest_ready_machine] := mach_avail_time[earliest_ready_machine] + proc_time_disc[j];

}